import turtle
def hello ():
    while True:
        a=turtle.Turtle()
        a.color("red")
        a.left(180)
        a.forward(320)
        a.right(90)
        a.forward(180)
        a.right(180)
        a.forward(90)
        a.left(90)
        a.forward(90)
        a.right(90)
        a.forward(90)
        a.right(180)
        a.forward(180)
        a.color("white")
        a.right(90)
        a.forward(60)
        a.color("dark green")
        a.forward(90)
        a.left(180)
        a.forward(90)
        a.left(90)
        a.forward(90)
        a.left(90)
        a.forward(90)
        a.left(180)
        a.forward(90)
        a.left(90)
        a.forward(90)
        a.left(90)
        a.forward(90)
        a.color("red")
        a.forward(50)
        a.color("dark blue")
        a.left(90)
        a.forward(180)
        a.left(180)
        a.forward(180)
        a.left(90)
        a.forward(90)
        a.color("red")
        a.forward(20)
        a.color("brown")
        a.left(90)
        a.forward(180)
        a.left(180)
        a.forward(180)
        a.left(90)
        a.forward(90)
        a.color("red")
        a.forward(10)
        a.color("black")
        a.forward(90)
        a.left(90)          
        a.forward(180)
        a.left(90)
        a.forward(90)
        a.left(90)
        a.forward(180)
hello()
    